### ISSUE TITLE
Handle muliple lines (like in VCARD)

### ISSUE THREAD

**Issue by theblackhole** [bmatcuk/flipperzero-qrcode#3]
Hello,

It would be nice to handle multiple lines like in [VCARD qr codes](https://www.evenx.com/vcard-3-0-format-specification) :)
Only the first line (`BEGIN:VCARD`) is parsed at the moment

**Comment by bmatcuk** [comment]
Sorry it took so long to get to this. I built this app in, basically, a weekend and then got busy with other things. I have finally found some free time to address feature requests for this app!

**Comment by theblackhole** [comment]
Thanks. I'll try your latest release.
And no worries, you don't have to justify yourself ;)

**Comment by bmatcuk** [comment]
Thanks =) I added a vcard example in the README and tested it with my f0 and iPhone - seems to work pretty well =) Little hard to get the phone to read the qrcode from the f0's small screen, but it does work.

**Comment by theblackhole** [comment]
I just tried your update and it worked flawlessly with several qr code readers app (including the default "Google Lens" one). Thanks for your work ! :)

**Comment by bmatcuk** [comment]
Nice! Glad it's working for you!
