### ISSUE TITLE
Publish to the new experimental app hub

### ISSUE THREAD

**Issue by theblackhole** [bmatcuk/flipperzero-qrcode#4]
Hello,

I think it would be great if you prepare your app and publish it to the new experimental app hub : https://github.com/flipperdevices/flipper-application-catalog
I would be easier for users to install and update it :)

**Comment by bmatcuk** [comment]
Thanks for the suggestion! I just submitted a PR: https://github.com/flipperdevices/flipper-application-catalog/pull/172

**Comment by doomwastaken** [comment]
Merged it! Thank you for contribution! A while back we were testing QR codes on flipper screen with different phones, works great

**Comment by bmatcuk** [comment]
The PR was merged two hours ago =)

**Comment by bmatcuk** [comment]
Thanks @doomwastaken!

**Comment by theblackhole** [comment]
![image](https://github.com/bmatcuk/flipperzero-qrcode/assets/7818904/974219cd-a6e6-4a64-8e8b-b3b558b52339)


Yay! :tada:

**Comment by bmatcuk** [comment]
Nice! Thanks for the screenshot! I actually haven't tried the app yet, so I didn't know what it would look like 😆
